site_name: DANDI Documentation
repo_name: "dandi/handbook"
repo_url: "https://github.com/dandi/handbook"
copyright: "CC-BY 4.0"
use_directory_urls: true
site_url: https://www.dandiarchive.org/handbook/

# This will use Material them
theme:
  name: "material"
  language: "en"
  favicon: img/favicon.png
  logo: img/dandi-logo-square_sw.png
  palette:
    primary: "dark blue"
    accent: "light blue"

# Pages
nav:
  - Welcome: "index.md"
  - Introduction: "01_introduction.md"
  - User Guide:
    - Using DANDI: "10_using_dandi.md"
    - Viewing Dandisets: "11_view.md"
    - Downloading Data and Dandisets: "12_download.md"
    - Creating Dandisets and Uploading Data: "13_upload.md"
    - Publishing Dandisets: "14_publish.md"
    - Debugging: "15_debugging.md"
  - Data Standards: "30_data_standards.md"
  - Developer Guide:
    - Project Structure: "20_project_structure.md"
    - Notes: "40_development.md"
  - Terms and Policies:
      - Terms: "about/terms.md"
      - Policies: "about/policies.md"
  - About This Doc: "100_about_this_doc.md"

# list of extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - toc:
      permalink: True
