site_name: DANDI Documentation
repo_name: "dandi/handbook"
repo_url: "https://github.com/dandi/handbook"
copyright: "CC-BY 4.0"
use_directory_urls: true
site_url: https://www.dandiarchive.org/handbook/

# Material theme
theme:
  name: "material"
  language: "en"
  favicon: img/favicon.ico
  logo: img/dandi-logo-square_sw.png
  palette:
    primary: "dark blue"
    accent: "light blue"
  features:
    - toc.integrate

# Pages
nav:
  - Welcome: "index.md"
  - Introduction: "01_introduction.md"
  - Data Standards: "30_data_standards.md"
  - Data Licenses: "35_data_licenses.md"
  - User Guide:
    - Using DANDI: "10_using_dandi.md"
    - Create DANDI Account: "16_account.md"
    - Viewing Dandisets: "11_view.md"
    - Downloading Data and Dandisets: "12_download.md"
    - Creating Dandisets and Uploading Data: "13_upload.md"
    - Validation Levels for NWB Files: "135_validation.md"
    - Publishing Dandisets: "14_publish.md"
    - Debugging: "15_debugging.md"
    - DANDI CLI and Python API: https://dandi.readthedocs.io
  - Developer Guide:
    - Project Structure: "20_project_structure.md"
    - Notes: "40_development.md"
    - REST API Swagger: https://api.dandiarchive.org/swagger
    - REST API Redoc: https://api.dandiarchive.org/redoc
  - DANDI Hub: "50_hub.md"
  - Terms and Policies:
      - Terms: "about/terms.md"
      - Policies: "about/policies.md"
  - About This Doc: "100_about_this_doc.md"

# List of extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - toc:
      permalink: True

# List of plugins
plugins:
  - search
  - open-in-new-tab

# Customize theme
extra:
  homepage: https://dandiarchive.org
  social:
    - icon: fontawesome/brands/slack
      link: https://dandiarchive.slack.com
      name: Slack
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@dandiarchive.org
      name: Email
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/dandiarchive
      name: X-Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/dandi
      name: GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dandiarchive
      name: YouTube
